services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    env_file:
      - .env

  mongo:
    image: "mongo:latest"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db # Persistent storage
      - ./mongo-user-init.js:/docker-entrypoint-initdb.d/mongo-user-init.js:ro # RBAC init script

volumes:
  mongo-data:
  caddy_data:
  caddy_config:
