// Package observability owns a process-local registry and bounded request logging.
package observability

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"log/slog"
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

type Observer struct {
	registry   *prometheus.Registry
	logger     *slog.Logger
	requests   *prometheus.CounterVec
	duration   *prometheus.HistogramVec
	cacheReads *prometheus.CounterVec
	cacheFills *prometheus.CounterVec
	failures   *prometheus.CounterVec
}

type requestIDKey struct{}

func New(logger *slog.Logger) *Observer {
	o := &Observer{
		registry: prometheus.NewRegistry(), logger: logger,
		requests:   prometheus.NewCounterVec(prometheus.CounterOpts{Name: "smallchop_http_requests_total", Help: "Completed application HTTP requests."}, []string{"route", "method", "status_class"}),
		duration:   prometheus.NewHistogramVec(prometheus.HistogramOpts{Name: "smallchop_http_request_duration_seconds", Help: "Application HTTP request duration, including limiting and dependency work.", Buckets: []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2, 5, 15, 60}}, []string{"route", "method", "status_class"}),
		cacheReads: prometheus.NewCounterVec(prometheus.CounterOpts{Name: "smallchop_cache_reads_total", Help: "Cache lookup outcomes; disabled cache does not perform a lookup."}, []string{"outcome"}),
		cacheFills: prometheus.NewCounterVec(prometheus.CounterOpts{Name: "smallchop_cache_fills_total", Help: "Cache fill outcomes after a successful storage lookup."}, []string{"outcome"}),
		failures:   prometheus.NewCounterVec(prometheus.CounterOpts{Name: "smallchop_dependency_failures_total", Help: "Failed application dependency operations; misses are excluded."}, []string{"dependency", "operation"}),
	}
	o.registry.MustRegister(o.requests, o.duration, o.cacheReads, o.cacheFills, o.failures)
	for _, outcome := range []string{"hit", "miss", "error"} {
		o.cacheReads.WithLabelValues(outcome)
	}
	for _, outcome := range []string{"success", "error"} {
		o.cacheFills.WithLabelValues(outcome)
	}
	for _, pair := range [][2]string{{"redis", "get"}, {"redis", "set"}, {"mongo", "find"}, {"mongo", "save"}, {"mongo", "ping"}} {
		o.failures.WithLabelValues(pair[0], pair[1])
	}
	return o
}

// MetricsHandler is served separately so scrapes do not count as application traffic.
func (o *Observer) MetricsHandler() http.Handler {
	mux := http.NewServeMux()
	mux.Handle("GET /metrics", promhttp.HandlerFor(o.registry, promhttp.HandlerOpts{MaxRequestsInFlight: 2}))
	return mux
}

// CacheRead accepts only the finite outcomes generated by the handler.
func (o *Observer) CacheRead(ctx context.Context, outcome string) {
	if o == nil {
		return
	}
	switch outcome {
	case "hit", "miss", "error":
	default:
		return
	}
	o.cacheReads.WithLabelValues(outcome).Inc()
	if outcome == "error" {
		o.DependencyFailure(ctx, "redis", "get")
	}
}

func (o *Observer) CacheFill(ctx context.Context, failed bool) {
	if o == nil {
		return
	}
	outcome := "success"
	if failed {
		outcome = "error"
	}
	o.cacheFills.WithLabelValues(outcome).Inc()
	if failed {
		o.DependencyFailure(ctx, "redis", "set")
	}
}

func (o *Observer) DependencyFailure(ctx context.Context, dependency, operation string) {
	if o == nil {
		return
	}
	// Reject unknown dimensions rather than let caller input create unbounded series.
	validRedis := dependency == "redis" && (operation == "get" || operation == "set")
	validMongo := dependency == "mongo" && (operation == "find" || operation == "save" || operation == "ping")
	if !validRedis && !validMongo {
		return
	}
	o.failures.WithLabelValues(dependency, operation).Inc()
	o.Warn(ctx, "dependency operation failed", "dependency", dependency, "operation", operation)
}

func (o *Observer) Warn(ctx context.Context, message string, attributes ...any) {
	if o == nil || o.logger == nil {
		return
	}
	id, _ := ctx.Value(requestIDKey{}).(string)
	o.logger.WarnContext(ctx, message, append(attributes, "request_id", id)...)
}

func (o *Observer) HTTP(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		var random [16]byte
		if _, err := rand.Read(random[:]); err != nil {
			http.Error(w, "Could not allocate request ID", http.StatusInternalServerError)
			return
		}
		id := hex.EncodeToString(random[:])
		w.Header().Set("X-Request-ID", id)
		r = r.WithContext(context.WithValue(r.Context(), requestIDKey{}, id))
		response := &responseWriter{ResponseWriter: w}
		next.ServeHTTP(response, r)
		status := response.status
		if status == 0 {
			status = http.StatusOK
		}
		route, method := routeLabel(r), methodLabel(r.Method)
		class := strconv.Itoa(status/100) + "xx"
		seconds := time.Since(start).Seconds()
		o.requests.WithLabelValues(route, method, class).Inc()
		o.duration.WithLabelValues(route, method, class).Observe(seconds)
		if o.logger != nil {
			o.logger.InfoContext(r.Context(), "http request completed", "request_id", id, "route", route, "method", method, "status", status, "duration_seconds", seconds)
		}
	})
}

func routeLabel(r *http.Request) string {
	switch r.Pattern {
	case "/":
		if r.URL.Path == "/" {
			return "/"
		}
	case "/shorten":
		return "/shorten"
	case "/r/":
		return "/r/{code}"
	case "/livez":
		return "/livez"
	case "/readyz":
		return "/readyz"
	}
	return "unmatched"
}

func methodLabel(method string) string {
	switch method {
	case "GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "CONNECT", "TRACE":
		return method
	}
	return "other"
}

type responseWriter struct {
	http.ResponseWriter
	status int
}

func (w *responseWriter) Unwrap() http.ResponseWriter { return w.ResponseWriter }
func (w *responseWriter) WriteHeader(status int) {
	if status >= 100 && status < 200 && status != http.StatusSwitchingProtocols {
		w.ResponseWriter.WriteHeader(status)
		return
	}
	if w.status != 0 {
		return
	}
	w.status = status
	w.ResponseWriter.WriteHeader(status)
}
func (w *responseWriter) Write(body []byte) (int, error) {
	if w.status == 0 {
		w.WriteHeader(http.StatusOK)
	}
	return w.ResponseWriter.Write(body)
}
