name: Go CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.23

            - name: Install dependencies
              run: |
                  go mod tidy
                  go mod download

            - name: Install golangci-lint
              run: |
                  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
              env:
                  PATH: ${{ runner.env.GOPATH }}/bin:${{ env.PATH }}

            - name: Build project
              run: |
                  go build ./...

    format:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run gofmt
              run: |
                  gofmt -s -w .

    lint:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run golangci-lint
              run: |
                  golangci-lint run

    tests:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run tests
              run: |
                  go test ./...
