name: CD Pipeline

on:
    push:
        branches:
            - main
    # This will be used only during setup, once GitHub action is confirmed working, will remove
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gochop-it .

            - name: Log in to DockerHub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Push Docker image
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gochop-it:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: SSH into DigitalOcean
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DO_HOST }}
                  username: ${{ secrets.DO_SSH_USER }}
                  key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
                  script: |
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gochop-it:latest
                      /usr/bin/docker-compose -f /root/gochop-it/docker-compose.yml down
                      /usr/bin/docker-compose -f /root/gochop-it/docker-compose.yml up -d
