name: Go CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.23

            - name: Install dependencies
              run: |
                  go mod tidy
                  go mod download

    format:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run gofmt
              run: |
                  gofmt -s -w .

    lint:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run Golangci-lint
              uses: golangci/golangci-lint-action@v6.1.1
              with:
                  version: latest
                  args: "--timeout 5m"

    tests:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run tests
              run: |
                  go test ./...
