name: Go CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: stable
                  cache-dependency-path: |
                      ./go.sum

            - name: Install dependencies
              run: |
                  go mod tidy
                  go mod download

    format:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run gofmt
              run: |
                  gofmt -s -w .
              working-directory: ./

    lint:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run Golangci-lint
              uses: golangci/golangci-lint-action@v6.1.1
              with:
                  version: v1.60
                  args: "--timeout 5m"
                  working-directory: ./

    tests:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run tests
              run: |
                  go test ./...
              working-directory: ./
